---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  jshint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "app/**.js"
  - "config/**.js"
exclude_paths:
- test/
- Gruntfile.js