---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  jshint:
    enabled: true
  scss-lint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "app/**/*.js"
  - "config/**/*.js"
  - "app/styles/**/*.scss"
exclude_paths:
- test/
- Gruntfile.js